apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=  # base64 encoded 'postgres'
  postgres-user: cG9zdGdyZXM=      # base64 encoded 'postgres'